# Environment name which should equal to Git branch name
master:

  # SSH user to be used in deployment
  user: richard

  # Server hostname or IP address for deployment
  hostname: 70.34.205.81
  
  # Path to deploy.
  deploy_path: /var/www/vhosts/mauritzschilderwerken.nl/httpdocs