# Environment name which should equal to Git branch name
master:

  # SSH user to be used in deployment
  user: root

  # Server hostname or IP address for deployment
  hostname: 70.34.199.155
  
  # Path to deploy.
  deploy_path: /var/www/html/wp-content/themes