# Environment name which should equal to Git branch name
master:

  # SSH user to be used in deployment
  user: richard@codeit.ninja

  # Server hostname or IP address for deployment
  hostname: prod.example.com
  
  # Path to deploy.
  deploy_path: /var/www/vhosts/mauritzschilderwerken.nl/httpdocs